apply plugin: 'com.android.library'

group = 'expo.modules.neptranslateocr'
version = '1.0.0'

android {
  namespace 'expo.modules.neptranslateocr'
  compileSdkVersion 35
  defaultConfig {
    minSdkVersion 24
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation 'com.google.mlkit:text-recognition:16.0.1'
  implementation 'com.google.mlkit:text-recognition-devanagari:16.0.1'
}
