// Static public-policy package; no runtime secrets, analytics or media.
const fs = require('node:fs');
const path = require('node:path');
const esbuild = require('../testing-ground/node_modules/esbuild');
const result = esbuild.buildSync({ stdin: { contents: 'export {en} from "./mobile/src/i18n/en"; export {ne} from "./mobile/src/i18n/ne";', resolveDir: process.cwd() }, bundle: true, format: 'cjs', platform: 'node', write: false, tsconfigRaw: {} });
const moduleObject = { exports: {} }; new Function('module', 'exports', result.outputFiles[0].text)(moduleObject, moduleObject.exports);
const { en, ne } = moduleObject.exports;
const root = path.join(__dirname, 'site'); fs.mkdirSync(root, { recursive: true });
const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const paragraphs = keys => keys.map(key => `<section><p lang="en">${escape(en[key])}</p><p lang="ne">${escape(ne[key])}</p></section>`).join('\n');
const shell = (title, content) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Bola English and Nepali translation, privacy and support"><title>${escape(title)} · Bola</title><link rel="stylesheet" href="/style.css"></head><body><header><a class="brand" href="/">Bola</a><nav aria-label="Main"><a href="/privacy.html">Privacy / गोपनीयता</a><a href="/terms.html">Terms / सर्त</a><a href="/support.html">Support / सहायता</a><a href="/deletion.html">Delete shared data / साझा डाटा मेटाऊ</a></nav></header><main><h1>${escape(title)}</h1>${content}</main><footer>Bola · English ↔ Nepali · Updated October 3, 2026</footer></body></html>`;
const pages = {
  'index.html': shell('English ↔ Nepali', '<p>Translation for iPhone and iPad. Translate text, speak, and read Camera results on your device.</p><p lang="ne">iPhone र iPad मा अङ्ग्रेजी ↔ नेपाली अनुवाद। पाठ, आवाज र क्यामेराको नतिजा आफ्नै यन्त्रमा प्रयोग गर।</p><p>Bola is currently in testing. These pages explain privacy, optional sharing and support.</p><p lang="ne">Bola अहिले परीक्षणमा छ। यी पृष्ठमा गोपनीयता, ऐच्छिक साझेदारी र सहायताबारे पढ।</p>'),
  'privacy.html': shell('Privacy Policy / गोपनीयता नीति', paragraphs(['startupConsent.privacy']) + '<h2>Optional model improvement / ऐच्छिक मोडेल सुधार</h2><p>Only optional contribution sharing requires age 18 or older. Ordinary app use and support do not.</p><p lang="ne">ऐच्छिक योगदान साझेदारीका लागि मात्र १८ वर्ष वा बढी उमेर चाहिन्छ। सामान्य एप प्रयोग र सहायताका लागि चाहिँदैन।</p>' + paragraphs(['privacy.consentSeparate','auth.contributionConsentBody','auth.ageConfirm','privacy.audioDisclosure','auth.withdrawConsentBody','auth.deleteAccountBody','privacy.installationWarning']) + '<h2>Private identity and providers / निजी पहिचान र प्रदायक</h2><p>Bola uses a private authenticated guest identity for credits, purchases, authorized sharing and deletion. Contributed content is linked to that identity and is not automatically anonymous or eligible for training or public display. Supabase provides private hosting/storage; Apple and RevenueCat process optional subscriptions; Google AdMob processes ad-related information when network ads are enabled. No advertising identifier (IDFA) is requested. Raw translations, recordings and photos are not sent to third-party analytics.</p><p lang="ne">क्रेडिट, खरिद, अनुमति दिएको साझेदारी र मेटाउने कार्यका लागि Bola ले निजी अतिथि पहिचान प्रयोग गर्छ। योगदान यो पहिचानसँग जोडिन्छ; आफैँ बेनाम वा प्रशिक्षण तथा सार्वजनिक प्रदर्शनका लागि योग्य हुँदैन। Supabase ले निजी होस्टिङ र भण्डारण, Apple र RevenueCat ले ऐच्छिक सदस्यता, Google AdMob ले विज्ञापन खुलेको बेला त्यससम्बन्धी जानकारी प्रशोधन गर्छन्। IDFA मागिँदैन। मूल अनुवाद, रेकर्डिङ वा फोटो तेस्रो पक्षको विश्लेषणमा पठाइँदैनन्।</p><h2>Support / सहायता</h2>' + paragraphs(['support.disclosure']) + '<p>Use <a href="/support.html">Support</a> for privacy questions. Contribution withdrawal and support-message deletion are separate controls.</p><p lang="ne">गोपनीयताबारे प्रश्नका लागि <a href="/support.html">सहायता</a> प्रयोग गर। योगदानको सहमति फिर्ता लिने र सहायता सन्देश मेटाउने विकल्प छुट्टाछुट्टै हुन्।</p>'),
  'terms.html': shell('Terms / नियम र सर्त', '<p>Bola provides English ↔ Nepali translation. Core translation, Camera, History and Learn do not require a subscription.</p><p lang="ne">Bola ले अङ्ग्रेजी ↔ नेपाली अनुवाद दिन्छ। अनुवाद, क्यामेरा, इतिहास र सिकाइका लागि सदस्यता चाहिँदैन।</p>' + '<p>Only optional contribution sharing requires age 18 or older. Ordinary app use and support do not.</p><p lang="ne">ऐच्छिक योगदान साझेदारीका लागि मात्र १८ वर्ष वा बढी उमेर चाहिन्छ। सामान्य एप प्रयोग र सहायताका लागि चाहिँदैन।</p>' + paragraphs(['privacy.consentSeparate','privacy.installationWarning','auth.deleteAccountBody']) + '<h2>Optional subscriptions / ऐच्छिक सदस्यता</h2><p>Ad-free is an optional monthly subscription. The App Store displays the localized price and billing terms before purchase. Manage or cancel it in Apple subscription settings. Deleting contributed data or a support message does not cancel a subscription.</p><p lang="ne">विज्ञापनरहित प्रयोग ऐच्छिक मासिक सदस्यता हो। खरिदअघि App Store ले स्थानीय मूल्य र भुक्तानी सर्त देखाउँछ। Apple को सदस्यता सेटिङबाट व्यवस्थापन वा रद्द गर। योगदान वा सहायता सन्देश मेटाउँदा सदस्यता रद्द हुँदैन।</p><p>App Store installations are subject to Apple’s applicable license terms. Read the <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/">Apple Standard EULA</a>. Read Bola’s <a href="/privacy.html">Privacy Policy</a> separately; general acceptance never grants permission to upload contributions.</p><p lang="ne">App Store बाट स्थापना गर्दा Apple का लागू इजाजत सर्त लागू हुन्छन्। <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/">Apple Standard EULA</a> र Bola को <a href="/privacy.html">गोपनीयता नीति</a> छुट्टै पढ। सामान्य स्वीकृतिले योगदान अपलोड गर्ने अनुमति दिँदैन।</p>'),
  'deletion.html': shell('Delete shared data / साझा डाटा मेटाऊ', '<p>In the original installation, open Settings → Privacy and data → Delete shared data. Withdrawal uses the same contribution-removal process.</p><p lang="ne">मूल स्थापनामा सेटिङ → गोपनीयता र डाटा → साझा डाटा मेटाऊ खोल। सहमति फिर्ता लिँदा पनि योगदान हटाउने यही प्रक्रिया प्रयोग हुन्छ।</p>' + paragraphs(['auth.withdrawConsentBody','auth.deleteAccountBody','privacy.installationWarning']) + '<p>Offline requests stop sharing locally and retry when connected. A scheduled deadline is not confirmation that deletion is finished. Support messages and replies have their own Delete control in Support.</p><p lang="ne">अफलाइन अनुरोधले स्थानीय साझेदारी रोक्छ र जडान भएपछि फेरि प्रयास गर्छ। तोकिएको मिति मेटाउने कार्य सकिएको पुष्टि होइन। सहायता सन्देश र जवाफका लागि सहायतामै छुट्टै मेटाउने विकल्प छ।</p>'),
  'support.html': shell('Support / सहायता', '<p>In the app, open Settings → Support. For an ad report, choose “Report inappropriate ad.” No email address is required. You can also use this private browser form.</p><p lang="ne">एपमा सेटिङ → सहायता खोल। विज्ञापनको रिपोर्टका लागि अनुपयुक्त विज्ञापन रिपोर्ट गर्ने विकल्प छान। इमेल चाहिँदैन। यहाँको निजी ब्राउजर फारम पनि प्रयोग गर्न सक्छौ।</p>' + paragraphs(['support.disclosure']) + '<p>Browser messages and replies belong to this browser’s private identity. Clearing browser storage can lose access; delete your requests first if you want them removed.</p><p lang="ne">ब्राउजरका सन्देश र जवाफ यस ब्राउजरको निजी पहिचानसँग जोडिन्छन्। ब्राउजरको भण्डारण हटाउँदा पहुँच हराउन सक्छ; सन्देश हटाउन चाहन्छौ भने पहिले मेटाऊ।</p><button id="start" type="button">Open private support / निजी सहायता खोल</button><form id="support-form"><label>Category / प्रकार<select id="category"><option value="general">General support / सामान्य सहायता</option><option value="ad">Ad report / विज्ञापन रिपोर्ट</option></select></label><label>Message / सन्देश<textarea id="message" maxlength="2000" required rows="6"></textarea></label><label class="choice"><input id="send-consent" type="checkbox" required>I choose to send this message for support / म सहायताका लागि यो सन्देश पठाउन रोज्छु</label><button type="submit">Send / पठाऊ</button></form><button id="refresh" type="button">Check replies / जवाफ हेर</button><p id="status" role="status"></p><div id="requests"></div><script type="module" src="/support.js"></script>'),
};
for (const [name, text] of Object.entries(pages)) fs.writeFileSync(path.join(root, name), text + '\n');
fs.writeFileSync(path.join(root,'style.css'), '*{box-sizing:border-box}body{margin:0;background:#fff9f3;color:#25221f;font-family:system-ui,sans-serif;line-height:1.6}header,main,footer{max-width:850px;margin:auto;padding:24px}header{border-bottom:1px solid #d2ab63}.brand{font-size:28px;font-weight:700}nav{display:flex;flex-wrap:wrap;gap:16px;margin-top:12px}a{color:#356b5a;text-underline-offset:3px}h1{font-size:32px}section{padding:8px 0;border-bottom:1px solid #e8dccb}[lang=ne]{line-height:1.85}label{display:block;margin:16px 0}textarea,select{display:block;width:100%;padding:12px;font:inherit;border:1px solid #d2ab63;border-radius:10px;background:white}button{min-height:44px;padding:10px 18px;margin:8px 8px 8px 0;border:1px solid #d2ab63;border-radius:10px;background:#fff;color:#356b5a;font:inherit;cursor:pointer}button:disabled{opacity:.5}.choice{display:flex;gap:12px;align-items:flex-start}article{padding:16px;border:1px solid #d2ab63;border-radius:12px;margin:16px 0;overflow-wrap:anywhere}footer{font-size:14px;color:#67605a}');
fs.writeFileSync(path.join(root,'app-ads.txt'), 'google.com, pub-4740685179017246, DIRECT, f08c47fec0942fa0\n');
fs.writeFileSync(path.join(root,'robots.txt'), 'User-agent: *\nAllow: /\n');
fs.writeFileSync(path.join(root,'.nojekyll'), '');
esbuild.buildSync({ entryPoints: [path.join(__dirname,'support.ts')], bundle: true, platform: 'browser', format: 'esm', outfile: path.join(root,'support.js'), tsconfigRaw: {}, minify: true });
console.log('Prepared bilingual policy/support site and root app-ads.txt. No publication.');
