"""New product prompts. Not drawn from benchmarks/gold."""

def _en(i: int, surface: str, register: str, text: str) -> dict:
    return {
        "id": f"bal_{i:04d}",
        "direction": "en-ne",
        "surface": surface,
        "register": register,
        "source_text": text,
        "review_status": "unapproved",
    }


def _roman(i: int, text: str) -> dict:
    return {
        "id": f"bal_{i:04d}",
        "direction": "ne-en",
        "surface": "roman_noise",
        "register": "noisy_roman",
        "source_text": text,
        "review_status": "unapproved",
    }


_YOU = [
    ("formal", "Could you tell me your name?"),
    ("informal", "What's your name?"),
    ("formal", "Would you please repeat that?"),
    ("informal", "Say that again?"),
    ("formal", "Are you waiting for someone?"),
    ("informal", "You waiting for someone?"),
    ("formal", "Can you help me with this form?"),
    ("informal", "Can you help me fill this out?"),
    ("formal", "Do you have a moment?"),
    ("informal", "You got a minute?"),
    ("formal", "Where are you from?"),
    ("informal", "Where you from?"),
    ("formal", "Did you understand me?"),
    ("informal", "Did you get what I said?"),
    ("formal", "Could you speak more slowly?"),
    ("informal", "Talk slower, okay?"),
    ("formal", "What would you like to drink?"),
    ("informal", "What do you want to drink?"),
    ("formal", "Are you feeling cold?"),
    ("informal", "You cold?"),
    ("formal", "Please tell me if you need anything."),
    ("informal", "Tell me if you need something."),
    ("formal", "Have you eaten yet?"),
    ("informal", "You eaten yet?"),
    ("formal", "May I ask you a question?"),
    ("informal", "Can I ask you something?"),
    ("formal", "Do you know the way from here?"),
    ("informal", "You know the way?"),
    ("formal", "Would you like me to call them?"),
    ("informal", "Want me to call them?"),
    ("formal", "Are you traveling alone?"),
    ("informal", "You here alone?"),
    ("formal", "Could you note that on paper for me?"),
    ("informal", "Write that down for me?"),
    ("formal", "What time do you close?"),
    ("informal", "When do you close?"),
    ("formal", "Do you take payment by card?"),
    ("informal", "You take cards?"),
    ("formal", "Is this seat free for you?"),
    ("informal", "You sitting here?"),
    ("formal", "Please let me know when you are ready."),
    ("informal", "Tell me when you're ready."),
    ("formal", "Did you bring your ticket?"),
    ("informal", "You bring your ticket?"),
    ("formal", "Can you hear me clearly?"),
    ("informal", "Can you hear me?"),
    ("formal", "Would you mind waiting outside?"),
    ("informal", "Wait outside a second?"),
    ("formal", "How long have you been here?"),
    ("informal", "How long you been here?"),
    ("formal", "Are you looking for the office?"),
    ("informal", "You looking for the office?"),
    ("formal", "Please call me when you arrive."),
    ("informal", "Call me when you get there."),
    ("formal", "Do you need a bag?"),
    ("informal", "You need a bag?"),
    ("formal", "Could you show me your identification?"),
    ("informal", "Can I see your ID?"),
    ("formal", "What is your phone number?"),
    ("informal", "What's your number?"),
    ("formal", "Are you allergic to anything?"),
    ("informal", "You allergic to anything?"),
    ("formal", "Would you prefer the window or the aisle?"),
    ("informal", "Window or aisle?"),
    ("formal", "Please tell me if you feel worse."),
    ("informal", "Tell me if you feel worse."),
    ("formal", "Do you want this in a smaller size?"),
    ("informal", "You want a smaller one?"),
    ("formal", "Can you meet me at the gate?"),
    ("informal", "Meet me at the gate?"),
    ("formal", "Have you been here before?"),
    ("informal", "You been here before?"),
    ("formal", "Would you like water while you wait?"),
    ("informal", "Want water while you wait?"),
    ("formal", "Please keep your bag with you."),
    ("informal", "Keep your bag with you."),
    ("formal", "Who are you here to see?"),
    ("informal", "Who you here to see?"),
    ("formal", "Could you confirm your address?"),
    ("informal", "What's your address again?"),
]
_TRAVEL = [
    "The next bus to Pokhara leaves at six.",
    "Is this the line for domestic departures?",
    "Our train is delayed by forty minutes.",
    "I need a ticket to the airport, one way.",
    "Where do I collect checked bags?",
    "The hotel is across from the old bus park.",
    "Please stop the taxi at the temple gate.",
    "How much is a shared jeep to the trailhead?",
    "I missed the last cable car down.",
    "Is there a night bus that has blankets?",
    "The guesthouse key is at the front desk.",
    "We have a reservation under the name Sharma.",
    "Which platform does the eastbound train use?",
    "The road to the village is closed after dark.",
    "Can I store this backpack until evening?",
    "The ferry leaves when it is full.",
    "I would like a room with a lock on the door.",
    "Where is the ticket counter for local buses?",
    "My flight connection is in thirty minutes.",
    "Please drop me near the footbridge, not the mall.",
    "Is drinking water sold on this bus?",
    "The mountain road is slippery after rain.",
    "I need to extend my stay by one night.",
    "Which stop is closest to the hospital?",
    "The driver said the pass is open today.",
    "Please write the lodge name in Nepali.",
    "We are looking for the trail marked with red paint.",
    "Is there a luggage rack above the seats?",
    "The border post closes at four.",
    "I left my jacket on the last bus.",
    "How long is the walk from this stop?",
    "Please slow down on the curves.",
    "We need two seats together if possible.",
    "The map shows a bridge that is not here.",
    "Is the museum open on Monday morning?",
    "I would like to pay the entrance fee for one adult.",
    "Where can I charge a phone for an hour?",
    "The homestay includes breakfast, not dinner.",
    "Please point toward the river path.",
    "Our guide will meet us by the blue gate.",
    "The altitude is making the climb slow.",
    "Is there a later jeep if we miss this one?",
    "Please keep the receipt for the park fee.",
    "The town center is two stops after the school.",
    "I need a place to sleep that is quiet.",
    "Which lane is for Kathmandu buses?",
    "The boatman asked us to wait on the sand.",
    "Please tell the driver we get off at the bazaar.",
    "We are lost between the temple and the market.",
    "Is the viewpoint worth the extra hour?",
]
_HEALTH = [
    "My head has hurt since last night.",
    "I feel dizzy when I stand up.",
    "The child has had a fever since morning.",
    "I am short of breath after one flight of stairs.",
    "Please look at this cut on my hand.",
    "I think I twisted my ankle on the path.",
    "The cough is worse at night.",
    "I need medicine for an upset stomach.",
    "She has not been able to keep water down.",
    "My tooth hurts on the left side.",
    "I am allergic to penicillin.",
    "The bandage keeps slipping off.",
    "Please check my blood pressure.",
    "I have a rash on both arms.",
    "The pain is here, under the ribs.",
    "I ran out of my daily tablets.",
    "He fainted for a few seconds and then woke.",
    "I need a clean cloth for this burn.",
    "The clinic told me to rest for two days.",
    "I cannot sleep because my ear aches.",
    "Please speak with the nurse, not only the desk.",
    "I feel nauseous in the moving bus.",
    "The swelling has not gone down.",
    "I need help reading this prescription.",
    "My back locked up while I was lifting a bag.",
    "The baby is crying and will not feed.",
    "I have chills but no fever yet.",
    "Please tell me if this pharmacy is open.",
    "I cut my foot on a rock in the river.",
    "The inhaler is empty.",
    "I need to lie down for a minute.",
    "The wound looks red around the edges.",
    "I have had diarrhea since yesterday.",
    "Please bring water before the tablets.",
    "My vision went blurry for a moment.",
    "I am diabetic and I missed lunch.",
    "The joint is hot and hard to bend.",
    "I need a doctor who can see me today.",
    "Please do not give me aspirin.",
    "I feel weak and my hands are shaking.",
]
_ROMAN = [
    "malai bau bata phone aako thiyo",
    "tapai kahile aaune ho",
    "yo bus pokhara jaancha ki jaandaina",
    "mero tauko dukhirako cha bihana dekhi",
    "kripaya bistarai bolnus",
    "hjr ko naam k ho",
    "maile ticket harayo",
    "yo bato band cha re",
    "malai ek glass thanda pani deu na",
    "timi kahile sutchau",
    "hospital kati tada cha",
    "mero khutta baliracha",
    "yo room ma taala cha?",
    "bholi bihana niskine",
    "maile bujina k bhandai",
    "sano baccha lai joro aako cha",
    "yo dawaa kati patak khane",
    "gadi ekchin rokdinus",
    "hami harayo bazaar ma",
    "phone charge hune thau cha?",
    "malai yeta samma pugauxa?",
    "rato get tira janu",
    "bato chipplo cha",
    "ma eklai hoina",
    "khana ali piro xa",
    "bato katiko lamo ho",
    "yo seat khali ho?",
    "malai ek glass pani dinus",
    "rato chinha wala bato",
    "ma pachi phone garchu",
]


def build() -> list[dict]:
    rows: list[dict] = []
    n = 1
    for register, text in _YOU:
        rows.append(_en(n, "conversation_you", register, text))
        n += 1
    for text in _TRAVEL:
        rows.append(_en(n, "travel", "formal", text))
        n += 1
    for text in _HEALTH:
        rows.append(_en(n, "health", "formal", text))
        n += 1
    for text in _ROMAN:
        rows.append(_roman(n, text))
        n += 1
    return rows


PROMPTS = build()
